hmcts/ccpay-service-request-cpo-update-service

build.gradle, src/main/java/uk/gov/hmcts/reform/services/CpoUpdateServiceImpl.java, src/test/java/uk/gov/hmcts/reform/services/CpoUpdateServiceTest.java
=> gradle version changed

src/main/java/uk/gov/hmcts/reform/services/CpoUpdateServiceImpl.java
=> test token

src/main/java/uk/gov/hmcts/reform/dtos/requests/CpoUpdateServiceRequest.java, src/main/resources/application.yaml
=> case if type changed to integer

src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/services/CpoUpdateServiceTest.java, src/test/java/uk/gov/hmcts/reform/services/ServiceBusMessageServiceTest.java
=> removed logging

src/main/resources/application.yaml
=> debug enable

src/main/java/uk/gov/hmcts/reform/services/CpoUpdateServiceImpl.java
=> Content-Type

src/test/java/uk/gov/hmcts/reform/services/CpoUpdateServiceTest.java
=> test content type

src/test/java/uk/gov/hmcts/reform/services/CpoUpdateServiceTest.java
=> test case fixes for response entity

Jenkinsfile_CNP
=> prod infra cnp added

Jenkinsfile_CNP
=> jenkins cnp

config/owasp/suppressions.xml, cve-resolution-strategy.gradle
=> Pr prod infra creation

Jenkinsfile_CNP
=> jenkinks cnp fix

config/owasp/suppressions.xml
=> dummy push

charts/ccpay-cpo-update-service/Chart.yaml, charts/ccpay-cpo-update-service/values.yaml, src/main/java/uk/gov/hmcts/reform/services/ServiceBusMessageServiceImpl.java
=> opening new PR for demo image pull

src/main/java/uk/gov/hmcts/reform/services/IdamServiceImpl.java
=> corrected IDAM URL in PROD

src/main/java/uk/gov/hmcts/reform/services/IdamServiceImpl.java
=> reverted IDAM URL fix

src/main/java/uk/gov/hmcts/reform/services/CpoUpdateServiceImpl.java, src/main/java/uk/gov/hmcts/reform/services/IdamServiceImpl.java
=> Fix idam url after cpo enabled

config/owasp/suppressions.xml
=> Extend cve suppressions

config/owasp/suppressions.xml
=> updated suppression file 

config/owasp/suppressions.xml
=> Suppressed - CVE-2022-42004, CVE-2022-42003

cve-resolution-strategy.gradle
=> Update tomcat embed version

cve-resolution-strategy.gradle
=> upgrade netty version for cve

config/owasp/suppressions.xml
=> suppressing cve, no fix available

charts/ccpay-cpo-update-service/Chart.yaml, cve-resolution-strategy.gradle
=> upgrading java chart to 4.0.12 and commons fileupload to v1.5

config/owasp/suppressions.xml
=> suppressed new cve

config/owasp/suppressions.xml, cve-resolution-strategy.gradle
=> CVE service request

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6334
Amended the suppression expiry date within the suppressions.xml file
```
[ ] Yes
[X] No
```
=> PAY-6334_suppression_expiry_update

infrastructure/main.tf
=> Add dependency for service bus subscription

.github/workflows/ci.yml, Dockerfile, build.gradle, config/owasp/suppressions.xml, cve-resolution-strategy.gradle, src/main/java/uk/gov/hmcts/reform/config/SwaggerConfiguration.java
PAY-6396: Updates the service request data to CPO
[PAY-6396] (https://tools.hmcts.net/jira/browse/PAY-6396).
=> PAY-6396: Updates the service request data to CPO

build.gradle, charts/ccpay-cpo-update-service/Chart.yaml, config/owasp/suppressions.xml, cve-resolution-strategy.gradle, gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PAY-6756
owasp dependency check upgrade
```
[ ] Yes
[X] No
```
=> PAY-6756 owasp upgrade

build.gradle, charts/ccpay-cpo-update-service/Chart.yaml, cve-resolution-strategy.gradle, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-5797
Infra update to create new topic on the new SB.
```
[ ] Yes
[x] No
```
=> PAY-5797: Update to add new SB Topic

.github/workflows/stale.yml
https://tools.hmcts.net/jira/browse/PAY-6981
https://tools.hmcts.net/jira/browse/PAY-6982
Auto close Bot Addition of stale.yml
```
[ ] Yes
[ x ] No
```
=> PAY-6982 PR Auto close Bot Addition of stale.yml

build.gradle, config/owasp/suppressions.xml, cve-resolution-strategy.gradle, src/main/java/uk/gov/hmcts/reform/services/CpoUpdateServiceImpl.java
https://tools.hmcts.net/jira/browse/PAY-7141
Fix to Medium CVE vulnerabilities.
Note, this includes an update to the microsoft libraries - need to check service bus messages get read.
```
[ ] Yes
[x] No
```
=> PAY-7141: Address Medium Vulnerabilities

build.gradle, cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-7141
Update as I missed spingboot upgrade.
```
[ ] Yes
[x] No
```
=> PAY-7141: Address Medium Vulnerabilities follow up

build.gradle
https://tools.hmcts.net/jira/browse/PAY-7303
Upgraded older libraries which was failing to pipeline.
```
[ ] Yes
[x] No
```
=> PAY-7303: Upgrade Libraries Pipeline Fix

.github/workflows/ci.yml, Dockerfile, build.gradle
https://tools.hmcts.net/jira/browse/CME-67
```
[ ] Yes
[ ] No
```
=> CME-67: Java 21

infrastructure/main.tf, infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-330
```
[ ] Yes
[ x] No
```
=> CME-330: Update azurerm

charts/ccpay-cpo-update-service/Chart.yaml
https://tools.hmcts.net/jira/browse/CME-425
```
[ ] Yes
[x ] No
```
=> CME-425: Update java and OCI endpoint

build.gradle
https://tools.hmcts.net/jira/browse/CME-529
Replace jitpack with azure
```
[ ] Yes
[x] No
```
=> CME-529 replace jitpack with azure
